
error in nav Dynamic server usage: Route /events couldn't be rendered statically because it used `cookies`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
root layout rendered
error in nav Dynamic server usage: Route /_not-found couldn't be rendered statically because it used `cookies`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
root layout rendered
error in nav Dynamic server usage: Route /signUp couldn't be rendered statically because it used `cookies`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
root layout rendered
sending req from booking
error in nav Dynamic server usage: Route /register couldn't be rendered statically because it used `cookies`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
root layout rendered
home rendering
error in nav Dynamic server usage: Route / couldn't be rendered statically because it used `cookies`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
from fetch_fnx fetch failed
from fetch_fnx fetch failed
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: fetch failed
    at async d (F:\React_Projects\Tech_takra-fullstack\frontend\.next\server\app\page.js:5:17063) {
  digest: '4065023895',
  [cause]: [Error: getaddrinfo ENOTFOUND computersciencesocietyonrender.com] {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'computersciencesocietyonrender.com'
  }
}
import {
  Geist,
  Geist_Mono,
  Inter,
  Poppins,
} from "next/font/google";

import "./globals.css";
import SmoothScroll from "./smooth_scroll";
import TanstackQueryClient from  "@/client_components/general_comps/tanstack_query_client";
// import WanderingHartNavbar from "./navBar";
import { Get_status } from "@/util_comps/nav_comp";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Inter for headings (700-900) and body (400-500)
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "700", "800", "900"],
});

// Poppins for sub-headings (500-700)
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["500", "600", "700"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children}) {

console.log("root layout rendered");


  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${poppins.variable} antialiased hide-scrollbar flex flex-col justify-center bg-gray-900 relative  max-w-screen min-h-screen   z-10 scrollbar-hide`}
      > 
      
    <div className="absolute inset-0 pointer-events-none z-0 
     bg-gray-900/40 h-full
     backdrop-saturate-150 
     border-t border-white/5 
     rounded-xl shadow-[0_0_40px_rgba(255,255,255,0.03)]">
</div> 


       <TanstackQueryClient>

        <Get_status/>
        <SmoothScroll>
        
        {children}
      
</SmoothScroll> 
 </TanstackQueryClient>
      </body>
    </html>
  );
}
