
import {
  
  Inter,
  Poppins,Cinzel,Playfair_Display
} from "next/font/google";

import "./globals.css";
import SmoothScroll from "./smooth_scroll";
import TanstackQueryClient from  "@/client_components/general_comps/tanstack_query_client";
// import WanderingHartNavbar from "./navBar";
import { Get_status } from "@/util_comps/nav_comp";




// Inter for headings (700-900) and body (400-500)
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "700", "800", "900"],
});

// Poppins for sub-headings (500-700)
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["500", "600", "700"],
});
const cinzel = Cinzel({
  variable: "--font-cinzel",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "GCU CSS Society",
  description: "Generated by create next app",
};

export default async function RootLayout({ children}) {

console.log("root layout rendered");


  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${poppins.variable} ${cinzel.variable} ${playfair.variable} antialiased hide-scrollbar flex flex-col justify-center bg-gray-900 relative  max-w-screen min-h-screen   z-10 scrollbar-hide`}
      > 
      
    <div className="absolute inset-0 pointer-events-none z-0 
     bg-gray-900/40 h-full
     backdrop-saturate-150 
     border-t border-white/5 
     rounded-xl shadow-[0_0_40px_rgba(255,255,255,0.03)]">
</div> 


       <TanstackQueryClient>

        <Get_status/>
        <SmoothScroll>
        
        {children}
      
</SmoothScroll> 
 </TanstackQueryClient>
      </body>
    </html>
  );
}
